config/routes.rb
Rails.application.routes.draw do

  root to: "paginas_estaticas#index"
  get '/contato', to: 'contatos#new', as: 'contatos'
  post '/contato', to: 'contatos#create'

  

end

app/views/layouts/_dashboard_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <div class="btn-group">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <%= @current_user.username if @current_user %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to 'Sair', logout_path %> </li>
            </ul>
          </div>
        </ul>
      </nav>
    </div>
  </div>
</header>

<script>
  $('.dropdown-toggle').dropdown()
</script>

app/views/layouts/_dashboard_sidebar.html.erb
<ul class="sf-menu">
  <li class="nav-header"> Menu </li>
  <li> <%= link_to 'Clientes', clientes_path %> </li>
  <li> <%= link_to 'Parceiros', users_path %> </li>
  <li> <%= link_to 'Atividades', atividades_path %> </li>
  <ul class="dropdown">
    <li> <%= link_to '#' do %> Emails <%= icon('angle-down') %> <% end %>
        <ul class="dropdown">
            <li> <%= link_to 'Plano Expirando', email_expiracao_plano_path %> </li>
            <li> <%= link_to 'Cadastro Realizado', email_cadastro_efetuado_path %> </li>
            <li> <%= link_to 'Pagamento Recebido', email_pagamento_recebido_path %> </li>
        </ul>
    </li>
  </ul>  
</ul>

app/views/layouts/_footer.html.erb
<footer class="site-footer-bottom">
  <div class="container">
    <div class="row">
      <div class="col-md-2"> <%= image_tag "societo-green.png", alt: "Societo",  class: "site-logo"%> </div>
                <div class="col-md-4">
                            </div>
                            <div class="col-md-6">
                                <ul class="social-icons-bar pull-right">
                                    <li><a href="#"><i class="fa fa-lg fa-facebook"></i></a>
                                    </li>
                                    <li><a href="#"><i class="fa fa-lg fa-twitter"></i></a>
                                    </li>
                                    <li><a href="#"><i class="fa fa-lg fa-google-plus"></i></a>
                                    </li>
                                    <li><a href="#"><i class="fa fa-lg fa-instagram"></i></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </footer>
<%= link_to icon('angle-double-up', '', id: 'back-to-top') %>

app/views/layouts/_header.html.erb
<header class="site-header" id="sticky-nav">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h1 class="logo"> <%= link_to image_tag("societo.png", alt: "Societo Clube de Vantagens"), root_path %> </h1>
      </div>
      <div class="col-md-9">
       
        <nav class="main-menu">
          <ul class="sf-menu" id="main-menu">
            <li> <%= link_to 'Societo', root_path %> </li>
            <li> <%= link_to 'Filie-se', nossos_planos_path %></li>
            <li> <%= link_to '#' do %> Cidades <%= icon('angle-down') %> <% end %>
              <ul class="dropdown">
                <li> <%= link_to 'Belo Horizonte', cidades_belo_horizonte_path %>
                    <ul class="dropdown">
                        <li> <%= link_to 'Societo Beer &amp; Wine', '#' %> </li>
                        <li> <%= link_to 'Societo Gourmet', '#' %> </li>
                        <li> <%= link_to 'Societo Night', '#' %> </li>
                        <li> <%= link_to 'Societo Shopping', '#' %> </li>
                    </ul>
                </li>
              </ul>
            </li>
            <li> <%= link_to 'Fale Conosco', contatos_path %> </li>
            <li> <%= link_to 'FAQ', faq_path %> </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>

  <nav class="mobile-menu">
    <div class="container">
      <div class="row"></div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html class="no-js">
	<%= yield :head %>
	<body>
		<div id="preloader">
		  <div id="status"></div>
		</div>
		<div class="body footer-style3 header-style6 landing-page"> 
			<%= yield %>
		</div>
	</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE HTML>
<html class="en">
	<%= yield :head %>
	<body style="overflow-x: scroll;">
		<div class="main" role="main">
		  <div id="content" class="content page-content full">
		    <div class="container">
		      <%= render 'layouts/dashboard_header' %>
		      <div class="row">
		        <div class="col-md-2  sidebar left-sidebar">
		        	<%= render 'layouts/dashboard_sidebar' unless (request.path.eql? new_atividade_path) %>
		          <div class="clearfix"></div>
		          <div id="message"></div>
		        </div>
				<div class="col-md-10">
		          <%= yield %>
		        </div>
		      </div>
		    </div>
		  </div>
		</div>
	</body>
</html>